title: Grace Guan
logo:  updated_grace_pic.png
#description: text below image
theme: jekyll-theme-minimal

email: "yaxingrace@gmail.com"
linkedin: grace-guan-0671881bb
# Build settings
markdown: kramdown
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"
