title: Grace Guan
email: yaxingrace@gmail.com
logo:  updated_grace_pic.png
#description: text below image
theme: jekyll-theme-minimal
user_country: Singapore
linkedin: www.linkedin.com/in/grace-guan-0671881bb


