title: Grace Guan
email: yaxingrace@gmail.com
logo:  updated_grace_pic.png
#description: text below image
theme: jekyll-theme-minimal

social:
  - name: LinkedIn
    icon: linkedin
    username: Grace Guan
    url: www.linkedin.com/in/grace-guan-0671881bb
    desc: Connect with me on LinkedIn
    share: true

